### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by nicolaslopezj** [orionjs/orion#78]
This issue tracks the process of the version 1.0

- [x] Relationships #33.
- [ ] Languages for entities #6.
- [ ] Clean up the code more, so its easier for people to contribute.
- [x] Merge all repositories into this one.
- [ ] Change current permission system to roles.
- [ ] New api for entities #76.
- [ ] Remove the default publication for entities #73.
- [ ] Create a new website.
- [ ] Write tests #77.
- [ ] Change the design of the admin.

Previews versions will not be compatible with the new one, but I will create a upgrade guide.

I will create a new branch so people who want to help can.

Maybe I will add more. 
I want to hear you comments

**Comment by timfam** [comment]
If we do it organically it will give everyone a chance to adapt to it without one single breaking release. As the new features come out, I will personally keep re-factoring my apps. I knew this would happen when I adopted meteor. I will say merging the repos should come first

**Comment by iamkevingreen** [comment]
This one might be a bit out of scope, but I'd love to see the bootstrap dependency removed from the admin. I might be interested in contributing to that actually because I loathe bootstrap. And maybe just clean up the default admin to be more modern looking.

**Comment by rwatts3** [comment]
Speaking of cleaning up the default admin I would love to see Inspinia Admin panel used with orion.  I simply like the look and field and it is clean and modern.

**Comment by rwatts3** [comment]
I have already purchased a subscription to inspinia admin so I get the latest updates and versions.  We could use that here.

**Comment by mraak** [comment]
I think the list is good. 

I wouldn't worry so much about the front end technology for admin. Look at Django, it went with something very simple for a long time until people created their own skins on various technologies, and you're now able to choose and use whatever you prefer.

**Comment by mraak** [comment]
> Clean up the code more, so its easier for people to contribute.

Also a small starting guide how to contribute.

**Comment by nicolaslopezj** [comment]
@iamkevingreen I will focus on making orion as separated as posible to bootstrap, but the default theme will still be in it.
You can create a custom theme!

**Comment by nicolaslopezj** [comment]
@rwatts3 I don't think the license of inpinia admin would allow this

**Comment by nicolaslopezj** [comment]
I changed the issue to a pull request #81
